name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Install Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.0.2
      with:
        go-version: '1.24'

    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Check formatting
      run: diff -u <(echo -n) <(gofmt -d .)

    - name: Check Go modules
      run: |
        go mod tidy
        git diff --exit-code

    - name: Run tests
      run: go test -v ./...

    - name: Run staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck -version
        staticcheck -- ./...

    - name: Run go vet
      run: go vet ./...
